# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: nideshop-mysql
    command:  mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - "~/app/nideshop/db:/var/lib/mysql"